//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\sanja\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://org84a1cc72.api.crm6.dynamics.com" /namespace:"SW365.OSIRIS.TableModel" /SuppressGeneratedCodeAttribute /out:"C:\Users\sanja\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\CrmServiceContext.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"sanjaya@subwind365.com" /password:"*************" 
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]
[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.95")]

namespace SW365.OSIRIS.TableModel
{
	
	/// <summary>
	/// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class CrmServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CrmServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.Account> AccountSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.Appointment"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.Appointment> AppointmentSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.Appointment>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.Contact> ContactSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.Incident"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.Incident> IncidentSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.Incident>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.IncidentResolution"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.IncidentResolution> IncidentResolutionSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.IncidentResolution>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_attendees"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_attendees> sw365_attendeesSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_attendees>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_casetype"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_casetype> sw365_casetypeSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_casetype>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_communityevent"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_communityevent> sw365_communityeventSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_communityevent>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_eventregistration"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_eventregistration> sw365_eventregistrationSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_eventregistration>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_membershipapproval"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_membershipapproval> sw365_membershipapprovalSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_membershipapproval>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_payment"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_payment> sw365_paymentSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_payment>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_subscription"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_subscription> sw365_subscriptionSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_subscription>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_subscriptiontype"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_subscriptiontype> sw365_subscriptiontypeSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_subscriptiontype>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.SystemUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.SystemUser> SystemUserSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.SystemUser>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.Task"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.Task> TaskSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.Task>();
			}
		}
	}
	
	internal sealed class EntityOptionSetEnum
	{
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public static System.Nullable<int> GetEnum(Microsoft.Xrm.Sdk.Entity entity, string attributeLogicalName)
		{
			if (entity.Attributes.ContainsKey(attributeLogicalName))
			{
				Microsoft.Xrm.Sdk.OptionSetValue value = entity.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>(attributeLogicalName);
				if (value != null)
				{
					return value.Value;
				}
			}
			return null;
		}
	}
	
	/// <summary>
	/// Attribute to handle storing the OptionSet's Metadata.
	/// </summary>
	[System.AttributeUsageAttribute(System.AttributeTargets.Field)]
	public sealed class OptionSetMetadataAttribute : System.Attribute
	{
		
		/// <summary>
		/// Color of the OptionSetValue.
		/// </summary>
		public string Color { get; set; }
		
		/// <summary>
		/// Description of the OptionSetValue.
		/// </summary>
		public string Description { get; set; }
		
		/// <summary>
		/// Display order index of the OptionSetValue.
		/// </summary>
		public int DisplayIndex { get; set; }
		
		/// <summary>
		/// External value of the OptionSetValue.
		/// </summary>
		public string ExternalValue { get; set; }
		
		/// <summary>
		/// Name of the OptionSetValue.
		/// </summary>
		public string Name { get; set; }
		
		/// <summary>
		/// Initializes a new instance of the <see cref="OptionSetMetadataAttribute"/> class.
		/// </summary>
		/// <param name="name">Name of the value.</param>
		/// <param name="displayIndex">Display order index of the value.</param>
		/// <param name="color">Color of the value.</param>
		/// <param name="description">Description of the value.</param>
		/// <param name="externalValue">External value of the value.</param>
		[System.Diagnostics.DebuggerNonUserCode()]
		public OptionSetMetadataAttribute(string name, int displayIndex, string color = null, string description = null, string externalValue = null)
		{
			this.Color = color;
			this.Description = description;
			this.ExternalValue = externalValue;
			this.DisplayIndex = displayIndex;
			this.Name = name;
		}
	}
	
	/// <summary>
	/// Extension class to handle retrieving of OptionSetMetadataAttribute.
	/// </summary>
	public static class OptionSetExtension
	{
		
		/// <summary>
		/// Returns the OptionSetMetadataAttribute for the given enum value
		/// </summary>
		/// <typeparam name="T">OptionSet Enum Type</typeparam>
		/// <param name="value">Enum Value with OptionSetMetadataAttribute</param>
		[System.Diagnostics.DebuggerNonUserCode()]
		public static OptionSetMetadataAttribute GetMetadata<T>(this T value)
			where T :  struct, System.IConvertible
		{
			System.Type enumType = typeof(T);
			if (!enumType.IsEnum)
			{
				throw new System.ArgumentException("T must be an enum!");
			}
			System.Reflection.MemberInfo[] members = enumType.GetMember(value.ToString());
			for (int i = 0; (i < members.Length); i++
			)
			{
				System.Attribute attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(members[i], typeof(OptionSetMetadataAttribute));
				if (attribute != null)
				{
					return ((OptionSetMetadataAttribute)(attribute));
				}
			}
			throw new System.ArgumentException("T must be an enum adorned with an OptionSetMetadataAttribute!");
		}
	}
}