#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW365.OSIRIS.TableModel
{
	
	
	/// <summary>
	/// Reason for the status of the Community Event
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sw365_communityevent_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sw365_communityevent_sw365_eventstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 1)]
		Active = 147980001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cancelled", 3)]
		Cancelled = 147980003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Completed", 2)]
		Completed = 147980002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("New", 0)]
		New = 147980000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Suspended", 4)]
		Suspended = 147980004,
	}
	
	/// <summary>
	/// Status of the Community Event
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sw365_communityeventState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("sw365_communityevent")]
	public partial class sw365_communityevent : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the sw365_communityevent entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string lk_sw365_communityevent_createdby = "lk_sw365_communityevent_createdby";
			public const string lk_sw365_communityevent_createdonbehalfby = "lk_sw365_communityevent_createdonbehalfby";
			public const string lk_sw365_communityevent_modifiedby = "lk_sw365_communityevent_modifiedby";
			public const string lk_sw365_communityevent_modifiedonbehalfby = "lk_sw365_communityevent_modifiedonbehalfby";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string statecodeName = "statecodename";
			public const string StatusCode = "statuscode";
			public const string statuscodeName = "statuscodename";
			public const string sw365_attendeecount = "sw365_attendeecount";
			public const string sw365_communityevent_sw365_eventregistration = "sw365_communityevent_sw365_eventregistration";
			public const string sw365_communityevent_sw365_eventticketprice = "sw365_communityevent_sw365_eventticketprice";
			public const string sw365_communityevent_sw365_payment = "sw365_communityevent_sw365_payment";
			public const string sw365_communityeventId = "sw365_communityeventid";
			public const string Id = "sw365_communityeventid";
			public const string sw365_description = "sw365_description";
			public const string sw365_eventcode = "sw365_eventcode";
			public const string sw365_eventenddate = "sw365_eventenddate";
			public const string sw365_eventstartdate = "sw365_eventstartdate";
			public const string sw365_eventstatus = "sw365_eventstatus";
			public const string sw365_eventstatusName = "sw365_eventstatusname";
			public const string sw365_eventtype = "sw365_eventtype";
			public const string sw365_eventtype_sw365_communityevent = "sw365_eventtype_sw365_communityevent";
			public const string sw365_eventtypeName = "sw365_eventtypename";
			public const string sw365_eventvenue = "sw365_eventvenue";
			public const string sw365_eventvenue_sw365_communityevent = "sw365_eventvenue_sw365_communityevent";
			public const string sw365_eventvenueName = "sw365_eventvenuename";
			public const string sw365_isguestsallowed = "sw365_isguestsallowed";
			public const string sw365_isguestsallowedName = "sw365_isguestsallowedname";
			public const string sw365_Name = "sw365_name";
			public const string sw365_numberofattendees = "sw365_numberofattendees";
			public const string sw365_registrationcount = "sw365_registrationcount";
			public const string sw365_registrationenddate = "sw365_registrationenddate";
			public const string sw365_registrationstartdate = "sw365_registrationstartdate";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string user_sw365_communityevent = "user_sw365_communityevent";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public sw365_communityevent() : 
				base(EntityLogicalName)
		{
		}
		
		public const string PrimaryIdAttribute = "sw365_communityeventid";
		
		public const string PrimaryNameAttribute = "sw365_name";
		
		public const string EntitySchemaName = "sw365_communityevent";
		
		public const string EntityLogicalName = "sw365_communityevent";
		
		public const string EntityLogicalCollectionName = "sw365_communityevents";
		
		public const string EntitySetName = "sw365_communityevents";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Community Event
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual sw365_communityeventState? StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((sw365_communityeventState?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StateCode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string statecodeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Community Event
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual sw365_communityevent_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((sw365_communityevent_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string statuscodeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_attendeecount")]
		public System.Nullable<int> sw365_attendeecount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("sw365_attendeecount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_attendeecount");
				this.SetAttributeValue("sw365_attendeecount", value);
				this.OnPropertyChanged("sw365_attendeecount");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_communityeventid")]
		public System.Nullable<System.Guid> sw365_communityeventId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("sw365_communityeventid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_communityeventId");
				this.SetAttributeValue("sw365_communityeventid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("sw365_communityeventId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_communityeventid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.sw365_communityeventId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_description")]
		public string sw365_description
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sw365_description");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_description");
				this.SetAttributeValue("sw365_description", value);
				this.OnPropertyChanged("sw365_description");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_eventcode")]
		public string sw365_eventcode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sw365_eventcode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_eventcode");
				this.SetAttributeValue("sw365_eventcode", value);
				this.OnPropertyChanged("sw365_eventcode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_eventenddate")]
		public System.Nullable<System.DateTime> sw365_eventenddate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("sw365_eventenddate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_eventenddate");
				this.SetAttributeValue("sw365_eventenddate", value);
				this.OnPropertyChanged("sw365_eventenddate");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_eventstartdate")]
		public System.Nullable<System.DateTime> sw365_eventstartdate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("sw365_eventstartdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_eventstartdate");
				this.SetAttributeValue("sw365_eventstartdate", value);
				this.OnPropertyChanged("sw365_eventstartdate");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_eventstatus")]
		public virtual sw365_communityevent_sw365_eventstatus? sw365_eventstatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((sw365_communityevent_sw365_eventstatus?)(EntityOptionSetEnum.GetEnum(this, "sw365_eventstatus")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_eventstatus");
				this.SetAttributeValue("sw365_eventstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("sw365_eventstatus");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_eventstatusname")]
		public string sw365_eventstatusName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("sw365_eventstatus"))
				{
					return this.FormattedValues["sw365_eventstatus"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_eventtype")]
		public Microsoft.Xrm.Sdk.EntityReference sw365_eventtype
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("sw365_eventtype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_eventtype");
				this.SetAttributeValue("sw365_eventtype", value);
				this.OnPropertyChanged("sw365_eventtype");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_eventtypename")]
		public string sw365_eventtypeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("sw365_eventtype"))
				{
					return this.FormattedValues["sw365_eventtype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_eventvenue")]
		public Microsoft.Xrm.Sdk.EntityReference sw365_eventvenue
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("sw365_eventvenue");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_eventvenue");
				this.SetAttributeValue("sw365_eventvenue", value);
				this.OnPropertyChanged("sw365_eventvenue");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_eventvenuename")]
		public string sw365_eventvenueName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("sw365_eventvenue"))
				{
					return this.FormattedValues["sw365_eventvenue"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_isguestsallowed")]
		public System.Nullable<bool> sw365_isguestsallowed
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("sw365_isguestsallowed");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_isguestsallowed");
				this.SetAttributeValue("sw365_isguestsallowed", value);
				this.OnPropertyChanged("sw365_isguestsallowed");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_isguestsallowedname")]
		public string sw365_isguestsallowedName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("sw365_isguestsallowed"))
				{
					return this.FormattedValues["sw365_isguestsallowed"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_name")]
		public string sw365_Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sw365_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_Name");
				this.SetAttributeValue("sw365_name", value);
				this.OnPropertyChanged("sw365_Name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_numberofattendees")]
		public System.Nullable<int> sw365_numberofattendees
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("sw365_numberofattendees");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_numberofattendees");
				this.SetAttributeValue("sw365_numberofattendees", value);
				this.OnPropertyChanged("sw365_numberofattendees");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_registrationcount")]
		public System.Nullable<int> sw365_registrationcount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("sw365_registrationcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_registrationcount");
				this.SetAttributeValue("sw365_registrationcount", value);
				this.OnPropertyChanged("sw365_registrationcount");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_registrationenddate")]
		public System.Nullable<System.DateTime> sw365_registrationenddate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("sw365_registrationenddate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_registrationenddate");
				this.SetAttributeValue("sw365_registrationenddate", value);
				this.OnPropertyChanged("sw365_registrationenddate");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_registrationstartdate")]
		public System.Nullable<System.DateTime> sw365_registrationstartdate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("sw365_registrationstartdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_registrationstartdate");
				this.SetAttributeValue("sw365_registrationstartdate", value);
				this.OnPropertyChanged("sw365_registrationstartdate");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N sw365_communityevent_sw365_eventregistration
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sw365_communityevent_sw365_eventregistration")]
		public System.Collections.Generic.IEnumerable<SW365.OSIRIS.TableModel.sw365_eventregistration> sw365_communityevent_sw365_eventregistration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SW365.OSIRIS.TableModel.sw365_eventregistration>("sw365_communityevent_sw365_eventregistration", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_communityevent_sw365_eventregistration");
				this.SetRelatedEntities<SW365.OSIRIS.TableModel.sw365_eventregistration>("sw365_communityevent_sw365_eventregistration", null, value);
				this.OnPropertyChanged("sw365_communityevent_sw365_eventregistration");
			}
		}
		
		/// <summary>
		/// 1:N sw365_communityevent_sw365_eventticketprice
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sw365_communityevent_sw365_eventticketprice")]
		public System.Collections.Generic.IEnumerable<SW365.OSIRIS.TableModel.sw365_eventticketprice> sw365_communityevent_sw365_eventticketprice
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SW365.OSIRIS.TableModel.sw365_eventticketprice>("sw365_communityevent_sw365_eventticketprice", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_communityevent_sw365_eventticketprice");
				this.SetRelatedEntities<SW365.OSIRIS.TableModel.sw365_eventticketprice>("sw365_communityevent_sw365_eventticketprice", null, value);
				this.OnPropertyChanged("sw365_communityevent_sw365_eventticketprice");
			}
		}
		
		/// <summary>
		/// 1:N sw365_communityevent_sw365_payment
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sw365_communityevent_sw365_payment")]
		public System.Collections.Generic.IEnumerable<SW365.OSIRIS.TableModel.sw365_payment> sw365_communityevent_sw365_payment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SW365.OSIRIS.TableModel.sw365_payment>("sw365_communityevent_sw365_payment", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_communityevent_sw365_payment");
				this.SetRelatedEntities<SW365.OSIRIS.TableModel.sw365_payment>("sw365_communityevent_sw365_payment", null, value);
				this.OnPropertyChanged("sw365_communityevent_sw365_payment");
			}
		}
		
		/// <summary>
		/// N:1 lk_sw365_communityevent_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_sw365_communityevent_createdby")]
		public SW365.OSIRIS.TableModel.SystemUser lk_sw365_communityevent_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<SW365.OSIRIS.TableModel.SystemUser>("lk_sw365_communityevent_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_sw365_communityevent_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_sw365_communityevent_createdonbehalfby")]
		public SW365.OSIRIS.TableModel.SystemUser lk_sw365_communityevent_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<SW365.OSIRIS.TableModel.SystemUser>("lk_sw365_communityevent_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_sw365_communityevent_createdonbehalfby");
				this.SetRelatedEntity<SW365.OSIRIS.TableModel.SystemUser>("lk_sw365_communityevent_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_sw365_communityevent_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_sw365_communityevent_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_sw365_communityevent_modifiedby")]
		public SW365.OSIRIS.TableModel.SystemUser lk_sw365_communityevent_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<SW365.OSIRIS.TableModel.SystemUser>("lk_sw365_communityevent_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_sw365_communityevent_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_sw365_communityevent_modifiedonbehalfby")]
		public SW365.OSIRIS.TableModel.SystemUser lk_sw365_communityevent_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<SW365.OSIRIS.TableModel.SystemUser>("lk_sw365_communityevent_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_sw365_communityevent_modifiedonbehalfby");
				this.SetRelatedEntity<SW365.OSIRIS.TableModel.SystemUser>("lk_sw365_communityevent_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_sw365_communityevent_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 sw365_eventtype_sw365_communityevent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_eventtype")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sw365_eventtype_sw365_communityevent")]
		public SW365.OSIRIS.TableModel.sw365_eventtype sw365_eventtype_sw365_communityevent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<SW365.OSIRIS.TableModel.sw365_eventtype>("sw365_eventtype_sw365_communityevent", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_eventtype_sw365_communityevent");
				this.SetRelatedEntity<SW365.OSIRIS.TableModel.sw365_eventtype>("sw365_eventtype_sw365_communityevent", null, value);
				this.OnPropertyChanged("sw365_eventtype_sw365_communityevent");
			}
		}
		
		/// <summary>
		/// N:1 sw365_eventvenue_sw365_communityevent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sw365_eventvenue")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sw365_eventvenue_sw365_communityevent")]
		public SW365.OSIRIS.TableModel.sw365_eventvenue sw365_eventvenue_sw365_communityevent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<SW365.OSIRIS.TableModel.sw365_eventvenue>("sw365_eventvenue_sw365_communityevent", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sw365_eventvenue_sw365_communityevent");
				this.SetRelatedEntity<SW365.OSIRIS.TableModel.sw365_eventvenue>("sw365_eventvenue_sw365_communityevent", null, value);
				this.OnPropertyChanged("sw365_eventvenue_sw365_communityevent");
			}
		}
		
		/// <summary>
		/// N:1 user_sw365_communityevent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_sw365_communityevent")]
		public SW365.OSIRIS.TableModel.SystemUser user_sw365_communityevent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<SW365.OSIRIS.TableModel.SystemUser>("user_sw365_communityevent", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public sw365_communityevent(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["sw365_communityeventid"] = base.Id;
                        break;
                    case "sw365_communityeventid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
#pragma warning restore CS1591
