adx_contentdisposition: 756150000
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: Product image 1.png
adx_parentpageid: a203e38f-0828-4fd7-8448-7c21b09934eb
adx_partialurl: Product image 1.png
adx_publishingstateid: 21fc0124-54c9-47d4-a847-2d9f48f2b1ff
adx_webfileid: e403fec9-e8bc-4cc4-8ad4-abd526007c4f
annotationid: 036e77d1-f0dd-ef11-a730-000d3a6aab35
filename: Product image 1.png
isdocument: true
mimetype: image/png
objectid: e403fec9-e8bc-4cc4-8ad4-abd526007c4f
objecttypecode: adx_webfile
