#pragma warning disable CS1591
// Created via this command line: PAC modelbuilder build --outdirectory C:\PROJECTS\SRC.OSIRIS\Code\SW365.OSIRIS.Solution\SW365.OSIRIS.TableModel --settingsTemplateFile C:\PROJECTS\SRC.OSIRIS\Code\SW365.OSIRIS.Solution\SW365.OSIRIS.TableModel\builderSettings.json
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace SW365.OSIRIS.TableModel
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class CrmServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public CrmServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.Account> AccountSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.ActivityPointer"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.ActivityPointer> ActivityPointerSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.ActivityPointer>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.Appointment"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.Appointment> AppointmentSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.Appointment>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.Incident"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.Incident> IncidentSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.Incident>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.IncidentResolution"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.IncidentResolution> IncidentResolutionSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.IncidentResolution>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_address"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_address> sw365_addressSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_address>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_attendees"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_attendees> sw365_attendeesSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_attendees>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_casetype"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_casetype> sw365_casetypeSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_casetype>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_communityevent"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_communityevent> sw365_communityeventSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_communityevent>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_eventregistration"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_eventregistration> sw365_eventregistrationSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_eventregistration>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_eventticketprice"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_eventticketprice> sw365_eventticketpriceSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_eventticketprice>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_eventtype"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_eventtype> sw365_eventtypeSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_eventtype>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_eventvenue"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_eventvenue> sw365_eventvenueSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_eventvenue>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_membershipapproval"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_membershipapproval> sw365_membershipapprovalSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_membershipapproval>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_payment"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_payment> sw365_paymentSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_payment>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_subscription"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_subscription> sw365_subscriptionSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_subscription>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.sw365_subscriptiontype"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.sw365_subscriptiontype> sw365_subscriptiontypeSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.sw365_subscriptiontype>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.SystemUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.SystemUser> SystemUserSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.SystemUser>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SW365.OSIRIS.TableModel.Task"/> entities.
		/// </summary>
		public System.Linq.IQueryable<SW365.OSIRIS.TableModel.Task> TaskSet
		{
			get
			{
				return this.CreateQuery<SW365.OSIRIS.TableModel.Task>();
			}
		}
	}
	
	/// <summary>
	/// Attribute to handle storing the OptionSet's Metadata.
	/// </summary>
	[System.AttributeUsageAttribute(System.AttributeTargets.Field)]
	public sealed class OptionSetMetadataAttribute : System.Attribute
	{
		
		private object[] _nameObjects;
		
		private System.Collections.Generic.Dictionary<int, string> _names;
		
		/// <summary>
		/// Color of the OptionSetValue.
		/// </summary>
		public string Color { get; set; }
		
		/// <summary>
		/// Description of the OptionSetValue.
		/// </summary>
		public string Description { get; set; }
		
		/// <summary>
		/// Display order index of the OptionSetValue.
		/// </summary>
		public int DisplayIndex { get; set; }
		
		/// <summary>
		/// External value of the OptionSetValue.
		/// </summary>
		public string ExternalValue { get; set; }
		
		/// <summary>
		/// Name of the OptionSetValue.
		/// </summary>
		public string Name { get; set; }
		
		/// <summary>
		/// Names of the OptionSetValue.
		/// </summary>
		public System.Collections.Generic.Dictionary<int, string> Names
		{
			get
			{
				return _names ?? (_names = CreateNames());
			} 
			set
			{
				_names = value;
				if (value == null)
				{
				    _nameObjects = new object[0];
				}
				else
				{
				    _nameObjects = null;
				}
			}
		}
		
		/// <summary>
		/// Initializes a new instance of the <see cref="OptionSetMetadataAttribute"/> class.
		/// </summary>
		/// <param name="name">Name of the value.</param>
		/// <param name="displayIndex">Display order index of the value.</param>
		/// <param name="color">Color of the value.</param>
		/// <param name="description">Description of the value.</param>
		/// <param name="externalValue">External value of the value.</param>
		/// <param name="names">Names of the value.</param>
		public OptionSetMetadataAttribute(string name, int displayIndex, string color = null, string description = null, string externalValue = null, params object[] names)
		{
			this.Color = color;
			this.Description = description;
			this._nameObjects = names;
			this.ExternalValue = externalValue;
			this.DisplayIndex = displayIndex;
			this.Name = name;
		}
		
		private System.Collections.Generic.Dictionary<int, string> CreateNames()
		{
			System.Collections.Generic.Dictionary<int, string> names = new System.Collections.Generic.Dictionary<int, string>();
			for (int i = 0; (i < _nameObjects.Length); i = (i + 2))
			{
				names.Add(((int)(_nameObjects[i])), ((string)(_nameObjects[(i + 1)])));
			}
			return names;
		}
	}
	
	/// <summary>
	/// Extension class to handle retrieving of OptionSetMetadataAttribute.
	/// </summary>
	public static class OptionSetExtension
	{
		
		/// <summary>
		/// Returns the OptionSetMetadataAttribute for the given enum value
		/// </summary>
		/// <typeparam name="T">OptionSet Enum Type</typeparam>
		/// <param name="value">Enum Value with OptionSetMetadataAttribute</param>
		public static OptionSetMetadataAttribute GetMetadata<T>(this T value)
			where T :  struct, System.IConvertible
		{
			System.Type enumType = typeof(T);
			if (!enumType.IsEnum)
			{
				throw new System.ArgumentException("T must be an enum!");
			}
			System.Reflection.MemberInfo[] members = enumType.GetMember(value.ToString());
			for (int i = 0; (i < members.Length); i++
			)
			{
				System.Attribute attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(members[i], typeof(OptionSetMetadataAttribute));
				if (attribute != null)
				{
					return ((OptionSetMetadataAttribute)(attribute));
				}
			}
			throw new System.ArgumentException("T must be an enum adorned with an OptionSetMetadataAttribute!");
		}
	}
}
#pragma warning restore CS1591
